Replace Logo component with a more idiomatic example
grommet/grommet-docs pull request #180
Opened 2016-11-30 04:36 UTC by jaitaiwan

Replaces the Logo component with a simple grommet Icon to prevent users from assuming there is a built in logo component with appropriate styling.

This addresses grommet/grommet/issues/1073

2016-11-30 04:38 UTC, jaitaiwan commented
Build appears to be failing due to not being able to execute `eval yarn`

2017-01-13 21:46 UTC, alansouzati requested changes

2017-01-13 21:46 UTC, alansouzati commented on src/docs/components/login-form/LoginFormDoc.js
> +            <dd>A react node. Best suited to an svg element or font icon.</dd>
can we remove the font icon? I don't think this is something we want to recommend. Also would you mind fixing the conflicts?

Sorry for taking such a long time to get back to you on this.

2017-01-13 22:07 UTC, tracybarmore commented
Hey @jaitaiwan. Sorry for the delayed feedback on this PR. Would you mind updating the pull request to remove the conflicts so we can successfully merge? Thanks for your contribution!

2017-01-14 00:15 UTC, jaitaiwan commented
I believe that with the requested changes my PR becomes pointless perhaps?

2017-01-18 19:23 UTC, alansouzati commented
I don't think so @jaitaiwan 

how about

```
A react node. Best suited to an svg element or a custom component containing an svg element.
```

2017-03-07 23:27 UTC, alansouzati commented
Fixed in https://github.com/grommet/grommet-docs/commit/3c7be98435a3670d61c09db5954112643edfa202

2017-03-07 23:27 UTC, closed without merging