Feat rc about page
grommet/grommet-docs pull request #233
Opened 2017-01-23 22:07 UTC by RyanCCollins

#### What does this PR do?
Adds an About page with info about the grommet team

#### Where should the reviewer start?
`src/docs/reference/About.js`

#### What testing has been done on this PR?
Manually tested by running in the browser.

#### How should this be manually tested?
Run in the browser and navigate to `http://localhost:8002/docs/about`

#### What are the relevant issues?
#162 

#### Screenshots (if appropriate)
![grommet about page](http://g.recordit.co/5KSeo29umR.gif)

2017-01-23 22:25 UTC, RyanCCollins commented
Added @ericsoderberghp's twitter account and fixed the eslint issues.

2017-01-23 23:45 UTC, alansouzati requested changes

2017-01-23 23:45 UTC, alansouzati commented on src/docs/reference/About.js
> +            two companies. The split became proof that G
I believe this a line break problem here? Not sure if it is affecting the actual page, but it seems odd to have "G" alone

2017-01-23 23:45 UTC, alansouzati commented on src/docs/reference/About.js
> +            customers—So that’s where we started.
Can we add spacing here?

2017-01-23 23:45 UTC, alansouzati commented on src/docs/reference/About.js
> +            to the community, but to our own eccosystem.
I think eccosystem should be ecosystem.

2017-01-23 23:45 UTC, alansouzati commented on src/docs/reference/About.js
> +            toolset and make better expeirences easier to create.
experiences

2017-01-23 23:45 UTC, alansouzati commented on src/docs/reference/About.js
> +            allow Grommet to be the leading React UI
can we say "one of the leading React UI .." :)

2017-01-23 23:48 UTC, RyanCCollins commented on src/docs/reference/About.js
> +            to the community, but to our own eccosystem.
Oops, I had just copy and pasted this and didn't think to spell check.  I will do a spell check and resubmit this.

2017-01-23 23:57 UTC, alansouzati commented on src/docs/reference/About.js
> +            to the community, but to our own eccosystem.
no problem man! thanks for looking into this in the first place.

2017-01-24 00:09 UTC, merged

2017-01-24 00:09 UTC, alansouzati commented
Thanks!

2017-01-24 00:24 UTC, RyanCCollins commented
Thank you! @alansouzati it looks like the images did not make it into the build :thinking: .  Any idea why that is?

2017-01-24 00:50 UTC, alansouzati commented
yeah it is because the confusing structure I set up for docs. I've fixed it in here:

https://github.com/grommet/grommet-docs/commit/90e2f91033058d6c9b1c13a8bbdc6dbba0c3e1cf

2017-01-24 00:57 UTC, RyanCCollins commented
Thank you sir!